version: '3.8'
services:
  api:
    image: plamer88/bewise-quiz:api-01
    env_file:
      - .env
    ports:
      - '80:8000'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      retries: 5
      interval: 5s
      timeout: 5s

volumes:
  postgres_data: